---
engines:
  duplication:
    config:
      languages:
        - "typescript"
    exclude_paths:
      - "src/abis/**/*.ts"
      - "tests/**/*.ts"
      - ".sonarlint/**/*"
      - ".github/**/*"
      - "diagrams/**/*"
      - "scripts/**/*"

exclude_paths:
  - "src/abis/**/*"
  - "tests/**/*"
  - ".sonarlint/**/*"
  - ".github/**/*"
  - "diagrams/**/*"
  - "vitest.config.ts"
  - "scripts/**/*"
include_paths:
  - "tests/integration/**/*"
