dependencies:
  - name: openzeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 5.1.0
  - name: aave
    github: aave-dao/aave-v3-origin
    version: 3.2.0

networks:
  polygon:
    mainnet:
      default_provider: alchemy
      alchemy:
        api_key: ${ALCHEMY_API_KEY}
    testnet:
      default_provider: alchemy
      alchemy:
        api_key: ${ALCHEMY_API_KEY}

test:
  mnemonic: test test test test test test test test test test test junk
  number_of_accounts: 2
  balance: 1 ETH

plugins:
  - name: solidity 
